config/routes.rb
Rails.application.routes.draw do

  resources :employees
  resources :documents
  get 'about' => 'pages#about_us'
  get 'contact' => 'pages#contact_us'
  get 'privicy' => 'pages#privicy_policy'
  get 'terms_and_conditions' => 'pages#term_and_conditions'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  #---------Two MEthods for define routs
  # get "home/index"
  # get '/home' => 'home#index'

  # for custom root
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :employee


  has_one_attached :image 

  DOC_TYPES=['Worksheet','Marks','Security','Others'].freeze

  validates :name, :doc_type, presence: true

end

app/models/employee.rb
class Employee < ApplicationRecord

    has_many :documents
 
    validates :first_name, :last_name, presence: true
    validates :personal_email , presence: true, uniqueness: true 
    validates :city, :state, :country , :pincode, :address_line_1,  presence: true

    def name
        "#{first_name} #{last_name}".strip 
    end

    def name_with_email
       "#{name} (#{personal_email})"
    end


    def full_addres
        "#{pincode}#{city}#{state}#{address_line_1}#{address_line_2}".strip
        end
    def address
    "#{address_line_1} #{address_line_2}".strip
    end

#This is the methodology of validate
    # validates :
# , presence: true, uniqueness: { case_sensitive: false }, length: {maximum: 50}, format: { with: ConstantData::VALID_EMAIL_REGEX }, if: :method_name?

employee= Employee.create(
first_name: "Ahsan  ",
last_name: "Ali",
personal_email: "ahsan@gmail.com",
city: "Johar town ",
state: "Lahore ",
country: "Pakistan ",
pincode: "4533 ",
address_line_1: "C2 phase ",
address_line_2: "main street "

)



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController

before_action :set_document, only: [:edit, :update, :show, :destroy]


 def index
    @documents = Document.all

 end

def new
    @document=Document.new
end

def edit
end
def show

end


def update 
    if @document.update(document_params)
      redirect_to documents_path, notice: "Document has been updated!"
  else
      render :edit
    end

  end

def create
    @document = Document.new(document_params)
    if @document.save
      redirect_to documents_path, notice: "Document successfully created"
    else
      flash[:error] = "Something went wrong"
      render :new
    end
end

def destroy
    if @document.destroy
      redirect_to documents_path, notice: "Document has been deleted"
    end
  end



private 
def document_params 
  params.require(:document).permit(:name, :doc_type, :employee_id, :image)
end 


   def set_document
      @document= Document.find(params[:id])
      rescue ActiveRecord::RecordNotFound => error
        redirect_to documents_path, notice:error
      end


end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController 


  before_action :set_employee, only: [:edit, :update, :show, :destory]



  def index
      @employees = Employee.all 
   end

 def new
    @employee = Employee.new

 end
  def edit 

  end

  def destroy
    if @employee.destroy
      redirect_to employees_path, notice: "Employee has been deleted"
    end
  end
  

  def update 
    if @employee.update(employee_params)
      redirect_to employees_path, notice: "Employee has been updated!"
  else
      render :edit
    end

  end
   
  def show 
   


  end
   

    def create
    @employee= Employee.new(employee_params)
    if @employee.save
        redirect_to employees_path, notice: "Employee has been created!"
    else
        render :new
      end
    end

  private 
   def employee_params 
    params.require(:employee).permit(:first_name, :last_name,:personal_email, :city, :state, :country , :pincode, :address_line_1, :address_line_2
    )
   end 

   def set_employee
      @employee= Employee.find(params[:id])
      rescue ActiveRecord::RecordNotFound => error
        redirect_to employees_path, notice:error

   end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
 
    def index
    @title_text = 'Hello World'
    @subtitle_text = 'I am learning Rails '
    end
    end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about_us
  end

  def contact_us
  end

  def privicy_policy
  end

  def term_and_conditions
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/documents/_form.html.erb
<%= form_with model: document do |form|  %>
    <div class="row">
    
    <div class="col-lg-4">
    <div class="form-group">
    <%= form.label   :name , class: "mb-2" %>
    <%= form.text_field :name , class: "form-control form-control-lg" %>
    <% @document.errors.full_messages_for(:name).each do |message| %>
        <p class="text-danger"><%= message %></p>
    <% end %>
    </div>
    </div>
    
    <div class="col-lg-4">
    <div class="form-group">
    <%= form.label   :doc_type , class: "mb-2" %>
    <%= form.select :doc_type, options_for_select(Document::DOC_TYPES, selected: document.doc_type) ,{prompt: 'Select Document type'}, { class: "form-select form-select-lg rounded-0"} %>
    <% @document.errors.full_messages_for(:doc_type).each do |message| %>
        <p class="text-danger"><%= message %></p>
    <% end %>
    </div>
    </div>
    <div class="col-lg-4">
    <div class="form-group">
    <%= form.label   :employee_id , class: "mb-2" %> 
    <%= form.select :employee_id, options_for_select(Employee.all.map{|employee|[employee.name_with_email, employee.id]}, selected: document.employee_id) ,{prompt: 'Select Employee'}, { class: "form-select form-select-lg rounded-0"} %>
    <% @document.errors.full_messages_for(:employee_id).each do |message| %>
        <p class="text-danger"><%= message %></p>
    <% end %>
    </div>
    </div>

    <div class="form-group mt-2">

    <%= form.label :image, class: "mb-2" %><br>
    <%= form.file_field :image %>


    </div>


    </div>
    <div class="row">
    <div class="col-lg-12 mt-3 text-center p-2">
    <%= form.submit class:"btn btn-success btn-lg rounded-0 text-center mx-4" %>
    <%= link_to "Back to Documents", documents_path , class:"btn btn-lg btn-outline-primary rounded-0 " %>
    
    </div>
    </div>

    <% end %>

app/views/documents/delete.html.erb
<div class="col-lg-12">
 <div class="card mt-5 mb-5 rounded-0">
 <div class="card-body">
 <h2 class="text-center">Delete Document</h2>
 </div>
 </div>


</div>

app/views/documents/edit.html.erb
<div class="col-lg-12">
 <div class="card mt-5 mb-5 rounded-0">
 <div class="card-body">
 <h2 class="text-center">Edit Document</h2>
 </div>
 </div>
 <%= render 'form', document: @document %>

</div>

app/views/documents/index.html.erb
<div class="col-lg-12">
<%= flash[:notice] %>
<div class="card mt-5 mb-5 rounded-0">
<div class="card-body">
<h2 class="text-center">Listing documents</h2>
</div>
</div>
<%= link_to "Create New document", new_document_path , class: "btn btn-primary btn-lg mb-4 rounded-0"  %>
<table class='table table-bordered'>
<thead >
<tr>

<th>Name</th>
<th>Document Type</th>

<th>Employee ID</th>
<th>Actions</th>


</tr>
</thead>

<tbody>
  <% @documents.each do |document| %>
   <tr> 
   <td><%= document.name %></td>
   <td><%= document.doc_type %></td>
   <td><%= document.employee_id %></td>
   <td >
   


   
  
   <div class="dropdown ">
  <button class="btn btn-primary opacity-85 dropdown-toggle " type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
    Perform  Actions
  </button>
  <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
    <li><%= link_to "View", document_path(document) , class: "btn btn-primary dropdown-item" %></li>
    <li>
    <%= link_to "Edit", edit_document_path(document), class: "btn btn-info dropdown-item" %></li>
    <li>
    <%= link_to "Delete", document_path(document), method: :delete, class: "btn btn-danger dropdown-item", data: { confirm: "Are You sure to delete this document" } %></li>
  </ul>
</div>

   
  </td>
   </tr>
  <% end %>
</tbody> 
</table>
</div>

app/views/documents/new.html.erb
<div class="col-lg-12">
 <div class="card mt-5 mb-5 rounded-0">
 <div class="card-body">
 <h2 class="text-center">Create New Document</h2>
 </div>
 </div>

<%= render 'form', document: @document %>

</div>

app/views/documents/show.html.erb
<div class="col-lg-12">
<div class="card mt-5 mb-5 rounded-0">
<div class="card-body">
<h2 class="text-center mb-5">Document Details</h2>

<div class="row ">
<div class="col-lg-6">
<h3>Document Information</h3>
<% if @document.image.attached? %>
    <%= image_tag @document.image %>
    <% else %>
  Image is not attached.
<% end %>
<p><strong> Name:</strong> <%= @document.name %></p>
<p><strong>Document Type:</strong> <%= @document.doc_type %></p>
<p><strong>Employee Id:</strong> <%= @document.employee_id %></p>
</div>
</div>




</div>
</div>

<%= link_to "Back to documents", documents_path , class:"btn btn-lg btn-outline-primary rounded-0 " %>

<%= link_to "Edit document", edit_document_path(@document), class: "btn btn-lg btn-outline-info rounded-0 " %>
</div>

app/views/employees/_form.html.erb
<%= form_with model: employee do |form|  %>
    <div class="row">
    

    <div class="col-lg-4">
    <div class="form-group">
    <%= form.label   :first_name , class: "mb-2" %>
    <%= form.text_field :first_name , class: "form-control form-control-lg" %>
    <% @employee.errors.full_messages_for(:first_name).each do |message| %>
        <p class="text-danger"><%= message %></p>
    <% end %>
    </div>
    </div>
    <div class="col-lg-4">
    <div class="form-group">
    <%= form.label   :last_name , class: "mb-2" %>
    <%= form.text_field :last_name , class: "form-control form-control-lg" %>
    <% @employee.errors.full_messages_for(:last_name).each do |message| %>
        <p class="text-danger"><%= message %></p>
    <% end %>
    </div>
    </div><div class="col-lg-4">
    <div class="form-group">
    <%= form.label   :personal_email , class: "mb-2" %>
    <%= form.email_field :personal_email , class: "form-control form-control-lg" %>
    <% @employee.errors.full_messages_for(:personal_email).each do |message| %>
        <p class="text-danger"><%= message %></p>
    <% end %>
    </div>
    </div>
    </div>
    <div class="row mt-3">
    <div class="col-lg-6">
    <div class="form-group ">
    <%= form.label   :address_line_1 , class: "mb-2" %>
    <%= form.text_field :address_line_1 , class: "form-control form-control-lg" %>
    <% @employee.errors.full_messages_for(:address_line_1).each do |message| %>
        <p class="text-danger"><%= message %></p>
    <% end %>
    </div>
    </div>
    <div class="col-lg-6">
    <div class="form-group">
    <%= form.label   :address_line_2 , class: "mb-2" %>
    <%= form.text_field :address_line_2 , class: "form-control form-control-lg" %>
    <% @employee.errors.full_messages_for(:address_line_2).each do |message| %>
        <p class="text-danger"><%= message %></p>
    <% end %>
    </div>
    </div>


    <div class="col-lg-3 mt-2">
    <div class="form-group">
    <%= form.label   :city , class: "mb-2" %>
    <%= form.text_field :city , class: "form-control form-control-lg" %>
    <% @employee.errors.full_messages_for(:city).each do |message| %>
        <p class="text-danger"><%= message %></p>
    <% end %>
    </div>
    </div><div class="col-lg-3  mt-2">
    <div class="form-group">
    <%= form.label   :state , class: "mb-2" %>
    <%= form.text_field :state , class: "form-control form-control-lg" %>
    <% @employee.errors.full_messages_for(:state).each do |message| %>
        <p class="text-danger"><%= message %></p>
    <% end %>
    </div>
    </div><div class="col-lg-3 mt-2">
    <div class="form-group">
    <%= form.label   :country , class: "mb-2" %>
    <%= form.text_field :country , class: "form-control form-control-lg" %>
    <% @employee.errors.full_messages_for(:country).each do |message| %>
        <p class="text-danger"><%= message %></p>
    <% end %>
    </div>
    </div>
    <div class="col-lg-3 mt-2">
    <div class="form-group">
    <%= form.label   :pincode , class: "mb-2" %>
    <%= form.text_field :pincode , class: "form-control form-control-lg" %>
    <% @employee.errors.full_messages_for(:pincode).each do |message| %>
        <p class="text-danger"><%= message %></p>
    <% end %>
    </div>
    </div>

    

    </div>
    <div class="row">
    <div class="col-lg-12 mt-3 text-center p-2">
    <%= form.submit class:"btn btn-success btn-lg rounded-0 text-center mx-4" %>
    <%= link_to "Back to Employees", employees_path , class:"btn btn-lg btn-outline-primary rounded-0 " %>
    
    </div>
    </div>
    
<% end %>

app/views/employees/delete.html.erb
<div class="col-lg-12">
 <div class="card mt-5 mb-5 rounded-0">
 <div class="card-body">
 <h2 class="text-center">Delete Employee</h2>
 </div>
 </div>


</div>

app/views/employees/edit.html.erb
<div class="col-lg-12">
 <div class="card mt-5 mb-5 rounded-0">
 <div class="card-body">
 <h2 class="text-center">Edit Employee</h2>
 </div>
 </div>
 <%= render 'form', employee: @employee %>

</div>

app/views/employees/index.html.erb
<div class="col-lg-12">
<%= flash[:notice] %>
<div class="card mt-5 mb-5 rounded-0">
<div class="card-body">
<h2 class="text-center">Listing Employees</h2>
</div>
</div>
<%= link_to "Create New Employee", new_employee_path , class: "btn btn-primary btn-lg mb-4 rounded-0"  %>
<table class='table table-bordered'>
<thead >
<tr>

<th>Name</th>
<th>Email</th>

<th>Adress</th>
<th>Actions</th>


</tr>
</thead>

<tbody>
  <% @employees.each do |employee| %>
   <tr> 
   <td><%= employee.name %></td>
   <td><%= employee.personal_email %></td>
   <td><%= employee.full_addres %></td>
   <td >
   


   
  
   <div class="dropdown ">
  <button class="btn btn-primary opacity-85 dropdown-toggle " type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
    Perform  Actions
  </button>
  <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
    <li><%= link_to "View", employee_path(employee) , class: "btn btn-primary dropdown-item" %></li>
    <li>
    <%= link_to "Edit", edit_employee_path(employee), class: "btn btn-info dropdown-item" %></li>
    <li>
    <%= link_to "Delete", employee_path(employee), method: :delete, class: "btn btn-danger dropdown-item", data: { confirm: "Are You sure to delete this employee" } %></li>
  </ul>
</div>

   
  </td>
   </tr>
  <% end %>
</tbody> 
</table>
</div>

app/views/employees/new.html.erb
<div class="col-lg-12">
 <div class="card mt-5 mb-5 rounded-0">
 <div class="card-body">
 <h2 class="text-center">Create New Employee</h2>
 </div>
 </div>
<%= form_with model: @employee do |form|  %>
    <div class="row">
    

    <div class="col-lg-4">
    <div class="form-group">
    <%= form.label   :first_name , class: "mb-2" %>
    <%= form.text_field :first_name , class: "form-control form-control-lg" %>
    <% @employee.errors.full_messages_for(:first_name).each do |message| %>
        <p class="text-danger"><%= message %></p>
    <% end %>
    </div>
    </div>
    <div class="col-lg-4">
    <div class="form-group">
    <%= form.label   :last_name , class: "mb-2" %>
    <%= form.text_field :last_name , class: "form-control form-control-lg" %>
    <% @employee.errors.full_messages_for(:last_name).each do |message| %>
        <p class="text-danger"><%= message %></p>
    <% end %>
    </div>
    </div><div class="col-lg-4">
    <div class="form-group">
    <%= form.label   :personal_email , class: "mb-2" %>
    <%= form.email_field :personal_email , class: "form-control form-control-lg" %>
    <% @employee.errors.full_messages_for(:personal_email).each do |message| %>
        <p class="text-danger"><%= message %></p>
    <% end %>
    </div>
    </div>
    </div>
    <div class="row mt-3">
    <div class="col-lg-6">
    <div class="form-group ">
    <%= form.label   :address_line_1 , class: "mb-2" %>
    <%= form.text_field :address_line_1 , class: "form-control form-control-lg" %>
    <% @employee.errors.full_messages_for(:address_line_1).each do |message| %>
        <p class="text-danger"><%= message %></p>
    <% end %>
    </div>
    </div>
    <div class="col-lg-6">
    <div class="form-group">
    <%= form.label   :address_line_2 , class: "mb-2" %>
    <%= form.text_field :address_line_2 , class: "form-control form-control-lg" %>
    <% @employee.errors.full_messages_for(:address_line_2).each do |message| %>
        <p class="text-danger"><%= message %></p>
    <% end %>
    </div>
    </div>


    <div class="col-lg-3 mt-2">
    <div class="form-group">
    <%= form.label   :city , class: "mb-2" %>
    <%= form.text_field :city , class: "form-control form-control-lg" %>
    <% @employee.errors.full_messages_for(:city).each do |message| %>
        <p class="text-danger"><%= message %></p>
    <% end %>
    </div>
    </div><div class="col-lg-3  mt-2">
    <div class="form-group">
    <%= form.label   :state , class: "mb-2" %>
    <%= form.text_field :state , class: "form-control form-control-lg" %>
    <% @employee.errors.full_messages_for(:state).each do |message| %>
        <p class="text-danger"><%= message %></p>
    <% end %>
    </div>
    </div><div class="col-lg-3 mt-2">
    <div class="form-group">
    <%= form.label   :country , class: "mb-2" %>
    <%= form.text_field :country , class: "form-control form-control-lg" %>
    <% @employee.errors.full_messages_for(:country).each do |message| %>
        <p class="text-danger"><%= message %></p>
    <% end %>
    </div>
    </div>
    <div class="col-lg-3 mt-2">
    <div class="form-group">
    <%= form.label   :pincode , class: "mb-2" %>
    <%= form.text_field :pincode , class: "form-control form-control-lg" %>
    <% @employee.errors.full_messages_for(:pincode).each do |message| %>
        <p class="text-danger"><%= message %></p>
    <% end %>
    </div>
    </div>

    

    </div>
    <div class="row">
    <div class="col-lg-12 mt-3 text-center p-2">
    <%= form.submit class:"btn btn-success btn-lg rounded-0 text-center mx-4" %>
    <%= link_to "Back to Employees", employees_path , class:"btn btn-lg btn-outline-primary rounded-0 " %>
    
    </div>
    </div>
    
    <% end %>
 </div>

app/views/employees/show.html.erb
    <div class="col-lg-12">
    <div class="card mt-5 mb-5 rounded-0">
    <div class="card-body">
    <h2 class="text-center mb-5">Employee Details</h2>

    <div class="row ">
    <div class="col-lg-6">
    <h3>Personal Information</h3>

    <p><strong>First Name:</strong> <%= @employee.first_name %></p>
    <p><strong>Last Name:</strong> <%= @employee.last_name %></p>
    <p><strong>Email:</strong> <%= @employee.personal_email %></p>
    </div>
    <div class="col-lg-6">
    <h3>Address Information</h3>

    <p><strong>Address:</strong> <%= @employee.address %></p>
    <p><strong>City:</strong> <%= @employee.city %></p>
    <p><strong>State:</strong> <%= @employee.state %></p>
    <p><strong>Country:</strong> <%= @employee.country %></p>
    <p><strong>Pin Code:</strong> <%= @employee.pincode %></p>

    </div>
    </div>




    </div>
    </div>

    <%= link_to "Back to Employees", employees_path , class:"btn btn-lg btn-outline-primary rounded-0 " %>
   
    <%= link_to "Edit Employee", edit_employee_path(@employee), class: "btn btn-lg btn-outline-info rounded-0 " %>
    </div>

app/views/home/index.html.erb
<h1><%= @title_text %></h1><br/>
<p><%=@subtitle_text %> </p>

<%= render 'shared/links' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HrManagementProjectInRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render 'shared/header' %>
  <div class='container'>
   <div class="row">
  <%= yield %>
   </div>
  </div>
    
  </body>
</html>

app/views/pages/about_us.html.erb
<div class="col-lg-10 mx-auto">
<h1>About Us</h1>
<%= render 'shared/dummy' %>
</div>
<%= render 'shared/links' %>

app/views/pages/contact_us.html.erb
<div class="col-lg-10 mx-auto">
  <h1>Contact Us</h1>
 <%= render 'shared/dummy' %>
</div>
<%= render 'shared/links' %>

app/views/pages/privicy_policy.html.erb
<div class="col-lg-10 mx-auto">
<h1>Privicy Policy</h1>
<%= render 'shared/dummy' %>
</div>
<%= render 'shared/links' %>

app/views/pages/term_and_conditions.html.erb
<div class="col-lg-10 mx-auto">
<h1>Terms and Condition</h1>
<%= render 'shared/dummy' %>
</div>
<%= render 'shared/links' %>

app/views/shared/_dummy.html.erb
<p class='lead'>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
<p class='lead'>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
<p class='lead'>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

app/views/shared/_footer.html.erb
<footer class="py-3 my-4">
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Home</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About Us</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Contact Us</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Privicy Policy</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Terms and Condition</a></li>
    </ul>
    <p class="text-center text-muted">© 2021 Company, Inc</p>
  </footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg  navbar-dark bg-primary">
  <div class="container-fluid">
    <%=  link_to "HR management", root_path, class: 'navbar-brand'
        
     %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="/about">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
      </ul>
      
    </div>
  </div>
</nav>

app/views/shared/_links.html.erb
 <footer class="py-3 my-4" >
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
<h1 class="px-4">HR Management</h1>
<li class="nav-item "> <%= link_to "About Us", about_path , target: '_blank',class:"nav-link px-4 mt-2" %></li>
 <li class="nav-item"> <%= link_to " Contact Us", contact_path , target: '_blank', class: "nav-link px-4 mt-2" %></li>
<li class="nav-item"> <%= link_to "Privicy", privicy_path , target: '_blank', class:"nav-link px-4 mt-2" %></li>
<li class="nav-item"> <%= link_to "Term and Conditions", terms_and_conditions_path , target: '_blank', class: "nav-link px-4 mt-2" %></li>

</ul>
    <p class="text-center text-muted">© 2021 Company, Inc</p>
</footer>